module "rds-ms-sql" {
  source = "./templates/rds-ms-sql"

  region = "us-west-2"
  identifier = "ican-db-dev"
  final-snapshot-identifier = "ican-db-final-snap-shot-dev"
  rds-allocated-storage = "20"
  rds-engine = "sqlserver-ex"
  engine-version = "14.00.3035.2.v1"
  db-instance-class = "db.t2.micro"
  backup-retension-period = "0"
  backup-window = "04:00-06:00"
  publicly-accessible = "false"
  rds-username = "sage"
  rds-password = "cbalallsooslsllsld11P4499Lcba1cba"
  multi-az = "false"
  storage-encrypted = "false"
  deletion-protection = "false"

  vpc-security-group-ids = "${module.rds-sg.aws-security-group-rds}"
  rds-private-subnets-groups-name = "ican-rds-private-subnets-group-dev"
  rds-private-subnets-groups-description = "Allowed Only Private Subnets for ican-ms-sql-dev"
  aws-db-subnet-group-private-subnets = "${module.vpc.private-subnet-ids}"
  name-aws-db-subnet-group = "ican-rds-subnets-groups-dev"
}
